spring.application.name=Enotes_Api_Service


# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/e-note-project
spring.datasource.username=root
spring.datasource.password=Jena@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate configuration (optional, but recommended)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
